import type { Transaction, Contractor, TaxSummary, EXPENSE_CATEGORIES } from './types.js';
import { TaxDatabase } from './database.js';
import { detectDuplicates, formatCurrency } from './utils.js';

export async function calculateSummary(db: TaxDatabase, taxYear: number): Promise<TaxSummary> {
  const transactions = await db.getAllTransactions();

  // Filter to tax year - handle both ISO and YYYY-MM-DD formats
  const yearTxs = transactions.filter(tx => {
    const dateStr = tx.date;
    // Extract year from YYYY-MM-DD or ISO format
    const yearMatch = dateStr.match(/^(\d{4})/);
    const txYear = yearMatch ? parseInt(yearMatch[1]) : new Date(dateStr).getFullYear();
    return txYear === taxYear;
  });
  
  // Calculate totals
  const totalIncome = yearTxs
    .filter(tx => tx.type === 'income')
    .reduce((sum, tx) => sum + tx.amount, 0);
  
  const totalExpenses = yearTxs
    .filter(tx => tx.type === 'expense')
    .reduce((sum, tx) => sum + tx.amount, 0);
  
  // Expense breakdown
  const expenseBreakdown: Record<string, number> = {};
  for (const tx of yearTxs.filter(tx => tx.type === 'expense')) {
    const cat = tx.category || 'Other';
    expenseBreakdown[cat] = (expenseBreakdown[cat] || 0) + tx.amount;
  }
  
  // Get contractors over $600
  const contractors = await db.getAllContractors();
  const contractorsOver600 = contractors.filter(c => c.totalPaid2025 >= 600);
  
  // Count duplicates
  const { duplicates } = detectDuplicates(yearTxs);
  
  return {
    taxYear,
    totalIncome,
    totalExpenses,
    netIncome: totalIncome - totalExpenses,
    contractorsOver600,
    expenseBreakdown,
    transactionCount: yearTxs.length,
    duplicateCount: duplicates.length,
  };
}

export async function identifyContractors(db: TaxDatabase): Promise<Contractor[]> {
  const transactions = await db.getAllTransactions();
  const contractors = await db.getAllContractors();
  
  // Group transactions by vendor
  const vendorTotals: Record<string, { total: number; txs: string[] }> = {};
  
  for (const tx of transactions) {
    if (tx.type !== 'expense') continue;
    if (tx.category !== 'Contract Labor') continue;
    
    const vendor = tx.vendor || 'Unknown';
    if (!vendorTotals[vendor]) {
      vendorTotals[vendor] = { total: 0, txs: [] };
    }
    vendorTotals[vendor].total += tx.amount;
    vendorTotals[vendor].txs.push(tx.id);
  }
  
  // Create/update contractors
  for (const [vendor, data] of Object.entries(vendorTotals)) {
    const existing = contractors.find(c => c.name === vendor);
    
    if (existing) {
      existing.totalPaid2025 = data.total;
      existing.transactions = data.txs;
      existing.needs1099 = data.total >= 600;
      await db.saveContractor(existing);
    } else {
      const newContractor: Contractor = {
        id: `contractor-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        name: vendor,
        totalPaid2025: data.total,
        transactions: data.txs,
        needs1099: data.total >= 600,
        issued1099: false,
      };
      await db.saveContractor(newContractor);
    }
  }
  
  return db.getAllContractors();
}

export function generateCPAPacket(summary: TaxSummary): string {
  const lines: string[] = [];
  
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('                    TAXSNAX CPA PACKET');
  lines.push('                        2025 Tax Year');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('');
  
  // Summary
  lines.push('📊 INCOME SUMMARY');
  lines.push(`   Total Income:    ${formatCurrency(summary.totalIncome)}`);
  lines.push(`   Total Expenses:  ${formatCurrency(summary.totalExpenses)}`);
  lines.push(`   Net Income:      ${formatCurrency(summary.netIncome)}`);
  lines.push('');
  
  // Expense breakdown
  lines.push('📑 EXPENSE BREAKDOWN');
  const sortedExpenses = Object.entries(summary.expenseBreakdown)
    .sort((a, b) => b[1] - a[1]);
  
  for (const [category, amount] of sortedExpenses) {
    lines.push(`   ${category.padEnd(25)} ${formatCurrency(amount).padStart(12)}`);
  }
  lines.push('');
  
  // 1099s
  if (summary.contractorsOver600.length > 0) {
    lines.push('👥 1099 CONTRACTORS (>$600)');
    for (const c of summary.contractorsOver600) {
      lines.push(`   ${c.name.padEnd(25)} ${formatCurrency(c.totalPaid2025).padStart(12)}`);
    }
    lines.push('');
    lines.push(`   Total 1099s needed: ${summary.contractorsOver600.length}`);
  } else {
    lines.push('👥 1099 CONTRACTORS: None over $600 threshold');
  }
  lines.push('');
  
  // Stats
  lines.push('📈 STATISTICS');
  lines.push(`   Total Transactions: ${summary.transactionCount}`);
  lines.push(`   Duplicates Removed: ${summary.duplicateCount}`);
  lines.push('');
  
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('Generated by TaxSnax v0.1.0');
  lines.push('Please review and verify all information before filing');
  lines.push('═══════════════════════════════════════════════════════════════');
  
  return lines.join('\n');
}

export function generate1099Summary(contractors: Contractor[]): string {
  const lines: string[] = [];
  
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('                    1099-MISC SUMMARY');
  lines.push('                        2025 Tax Year');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('');
  
  const needing1099 = contractors.filter(c => c.needs1099 && !c.issued1099);
  
  if (needing1099.length === 0) {
    lines.push('No 1099s pending issuance.');
  } else {
    lines.push(`Pending 1099s: ${needing1099.length}`);
    lines.push('');
    
    for (const c of needing1099) {
      lines.push(`   Name:     ${c.name}`);
      lines.push(`   Amount:   ${formatCurrency(c.totalPaid2025)}`);
      lines.push(`   Email:    ${c.email || 'NEEDED'}`);
      lines.push(`   Address:  ${c.address || 'NEEDED'}`);
      lines.push(`   SSN/EIN:  ${c.ssn || c.ein || 'NEEDED'}`);
      lines.push('');
    }
    
    lines.push('⚠️  ACTION REQUIRED:');
    lines.push('   Collect missing information for W-9s');
    lines.push('   Issue 1099-NEC forms by January 31, 2026');
  }
  
  lines.push('');
  lines.push('═══════════════════════════════════════════════════════════════');
  
  return lines.join('\n');
}
